PACKAGE_SOURCE="/mnt/hdd1/Games/Non Steam/hex-free/package.nw/"



#No need to change unless you know what you are doing
APP_NAME="Hex"
DESKTOP_FILENAME="Hex.desktop"
ICON_PATH="/assets/favicon.png"
EXECUTABLE="nw"
FORCE=false

PACKAGE_LINK="package.nw"
NWJS_VERSION="0.94.0"
ARCH="linux-x64"
BUILD="normal"
